### ISSUE TITLE
fatal error: 'Block.h' file not found

### ISSUE THREAD

**Issue by RonakKosamia** [mlabbe/CoreFoundation#1]
fatal error: 'Block.h' file not found

[arm64-v8a] Compile        : sampler <= CFApplicationPreferences.c
In file included from /Users/ro/sampler/MySumNdk/app/src/main/jni/CoreFoundation/CFApplicationPreferences.c:29:
In file included from /Users/ro/sampler/MySumNdk/app/src/main/jni/CoreFoundation/CFPreferences.h:31:
/Users/ro/sampler/MySumNdk/app/src/main/jni/CoreFoundation/CFBase.h:90:10: fatal error: 'Block.h' file not found
#include <Block.h>
         ^
1 error generated.
make: *** [/Users/ro/sampler/MySumNdk/app/src/main/obj/local/arm64-v8a/objs/sampler/CoreFoundation/CFApplicationPreferences.o] Error 1

**Comment by mlabbe** [comment]
H, please consider this an unsupported project.  I did the port awhile ago and haven't maintained it.  I've also forgotten most of what I did to get it to build.

block.h, however, I can tell you is from the Clang blocks implementation.

**Comment by RonakKosamia** [comment]
Thanks
